"""Synthetic Dirichlet--multinomial router fixtures for evidence-gate tests.

These build the ``keep`` and ``split`` affected-region transition counts for the
canonical Stage-2 edit (SI S3.4/S3.5): a parent node whose events are generated by
two sub-populations with distinct outgoing routing. Representing them as one node
forces a high-entropy blended outgoing distribution; splitting into two children
gives each child a concentrated (low-entropy) distribution, whose
Dirichlet--multinomial marginal is larger. The evidence margin favouring the true
(split) topology grows as ``O(H_R * Delta_R)`` with ``Delta_R = log 2`` at full
separation (SI S3.5).
"""
from __future__ import annotations

import numpy as np

from proteus.evidence import NodeTransition, bdeu_alpha


def two_subpopulation_counts(
    n_events: int,
    sep: float,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return ``(keep_counts, child1_counts, child2_counts)`` over outcomes {X, Y}.

    ``n_events`` are split evenly between two sub-populations. Sub-population 1
    routes to X with probability ``sep`` (Y otherwise); sub-population 2 routes to
    Y with probability ``sep`` (X otherwise). ``sep = 1`` is perfectly separated
    (each child deterministic), ``sep = 0.5`` is genuine no-substructure.
    """

    n_half = n_events // 2
    x1 = int(rng.binomial(n_half, sep))
    y1 = n_half - x1
    y2 = int(rng.binomial(n_half, sep))
    x2 = n_half - y2
    keep = np.array([x1 + x2, y1 + y2], dtype=float)
    child1 = np.array([x1, y1], dtype=float)
    child2 = np.array([x2, y2], dtype=float)
    return keep, child1, child2


def split_regions(
    n_events: int,
    *,
    sep: float = 0.98,
    d_final: int = 1,
    rng: np.random.Generator | None = None,
) -> tuple[list[NodeTransition], list[NodeTransition]]:
    """Build (keep_region, split_region) NodeTransition lists (SI S3.4).

    keep_region: one parent node routing over {X, Y}. split_region: two child
    nodes, each routing over {X, Y}. Both use BDeu concentration
    ``alpha_0 = 1/(d_final + 1)`` (SI S2.7).
    """

    rng = rng or np.random.default_rng(0)
    a0 = bdeu_alpha(d_final)
    keep, c1, c2 = two_subpopulation_counts(n_events, sep, rng)
    keep_region = [NodeTransition(keep, 2, a0, node_id=0)]
    split_region = [
        NodeTransition(c1, 2, a0, node_id=0),
        NodeTransition(c2, 2, a0, node_id=1),
    ]
    return keep_region, split_region
