"""Evidence scoring and structure-selection gates (SI S3.4-S3.6, S10.4)."""

from proteus.evidence.dm_score import (
    NodeTransition,
    bdeu_alpha,
    evaluate_edit,
    f_dm,
    node_log_marginal,
)
from proteus.evidence.gate import (
    DualAdjacency,
    EvidenceGate,
    FailClosedDryRunEvidenceCase,
    FailClosedDryRunEvidenceProbe,
    FailClosedDryRunReconnectCase,
    FailClosedDryRunReconnectProbe,
    FailClosedEvidenceGateCaseResult,
    FailClosedEvidenceGateMatrixProbe,
    FailClosedScoreEditCase,
    FailClosedScoreEditMatrixProbe,
    GateConfig,
    affected_dual_subgraph_connected,
    edit_budget,
    gate_window,
    hysteresis_window,
    probe_fail_closed_dry_run_evidence_gate,
    probe_fail_closed_dry_run_reconnect_bridge,
    probe_fail_closed_evidence_gate_matrix,
    probe_fail_closed_score_edit_matrix,
    score_edit,
)
from proteus.evidence.star_matrix import (
    RHO_MIN_CONSERVATIVE,
    RHO_MIN_DEFAULT,
    condition_ratio,
    is_evidence_bearing,
    quarantined_nodes,
    star_incidence_matrix,
)

__all__ = [
    "NodeTransition",
    "bdeu_alpha",
    "node_log_marginal",
    "f_dm",
    "evaluate_edit",
    "star_incidence_matrix",
    "condition_ratio",
    "is_evidence_bearing",
    "quarantined_nodes",
    "RHO_MIN_DEFAULT",
    "RHO_MIN_CONSERVATIVE",
    "DualAdjacency",
    "GateConfig",
    "FailClosedScoreEditCase",
    "FailClosedScoreEditMatrixProbe",
    "FailClosedEvidenceGateCaseResult",
    "FailClosedEvidenceGateMatrixProbe",
    "FailClosedDryRunEvidenceCase",
    "FailClosedDryRunEvidenceProbe",
    "FailClosedDryRunReconnectCase",
    "FailClosedDryRunReconnectProbe",
    "gate_window",
    "hysteresis_window",
    "edit_budget",
    "affected_dual_subgraph_connected",
    "score_edit",
    "probe_fail_closed_score_edit_matrix",
    "probe_fail_closed_evidence_gate_matrix",
    "probe_fail_closed_dry_run_evidence_gate",
    "probe_fail_closed_dry_run_reconnect_bridge",
    "EvidenceGate",
]
